apiVersion: v1
kind: Service
metadata:
  name: tnnbiotgateway-lab-prd-tcp
spec:
  type: LoadBalancer
  selector:
    app: tnnbiotgateway-lab-prd
  ports:
  - port: 80
    name: http80
  - port: 8080
    name: http8080
  - port: 3000
    name: http3000